spring.application.name=product-stream

spring.r2dbc.url=r2dbc:h2:mem:///testdb?options=DB_CLOSE_DELAY=-1
spring.r2dbc.username=sa
spring.r2dbc.password=

spring.sql.init.mode=always

app.exchange-rate.url=http://localhost:8082