spring:
  application:
    name: ticket-reservation
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password:

app:
  event:
    url: http://localhost:9080
  wallet:
    url: http://localhost:9080


resilience4j:
  circuitbreaker:
    instances:
      wallet:
        sliding-window-size: 5
        failure-rate-threshold: 50.0
        wait-duration-in-open-state: 3s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true