spring.application.name=shipping-router

spring.r2dbc.url=r2dbc:h2:mem:///testdb
spring.r2dbc.username=sa
spring.r2dbc.password=


app.courier.url=http://localhost:9080
app.quoter.url=http://localhost:9080

resilience4j.circuitbreaker.instances.courier.sliding-window-size=5
resilience4j.circuitbreaker.instances.courier.failure-rate-threshold=50.0
resilience4j.circuitbreaker.instances.courier.wait-duration-in-open-state=3s
resilience4j.circuitbreaker.instances.courier.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.courier.automatic-transition-from-open-to-half-open-enabled=true